[project]
name = "mcp-client"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "anthropic>=0.49.0",
    "awscli>=1.38.34",
    "boto3>=1.37.34",
    "mcp>=1.6.0",
    "pandas>=2.2.3",
    "pyarrow>=19.0.1",
    "pyiceberg>=0.9.0",
    "python-dotenv>=1.1.0",
    "tabulate>=0.9.0",
]
